# Uncomment the next line to define a global platform for your project
# platform :ios, '13.0'

target 'bootstrap' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for bootstrap
    pod 'PromisesSwift'
    pod 'SDWebImageSwiftUI'
    pod 'SwiftyBeaver'

  target 'bootstrapTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'bootstrapUITests' do
    # Pods for testing
  end

end
